### ISSUE TITLE
I don't think ROS2 is liking this

### ISSUE THREAD

**Issue by tiptonnet** [Rad-hi/Obstacle-Avoidance-ROS#1]
ROS2 Humble
Ubuntu 22.04
Intel NUC

ros2 run basic_mobile_robot scripts/laser_obstacle_avoid_360_node_class.py
No executable found

I sourced ROS and my install.bash

**Comment by Rad-hi** [comment]
This is a ROS1 project, I haven't tried it with ROS2 yet.
I would put this into a package and build before running it.

**Comment by Rad-hi** [comment]
closing for being stale for so long.
